package com.solarenchants.enchantments;

public enum CustomEnchants {

    TELEPATHY, HASTE, SMELTER, EXPERIENCE, POISON, FREEZING, UNBREAKABLE, EXPLOSION, NIGHTSEEKER, ESCAPIST, CURSE, TURTLE, AUTOSELL, OREDETECTOR, BARBARIAN, ENDERMAN,
    NINJA, EXPLOSIVE, MOLOTOV, BLAZE, BOMBARDMENT, FIREWORKS, BUNNY; 

}
